name: Release Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Build:
    name: Build/Sign APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Tag
        id: var
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Access Api keys
        env:
          apiKey: ${{ secrets.API_KEY }}
          path: app/src/main/res/values/secrets.xml
        run: |
          touch $path
          echo \<resources\> >> $path
          echo \<string name=\"google_maps_key\"\>$apiKey\</string\> >> $path
          echo \</resources\> >> $path

      - name: Build APK
        run: bash ./gradlew assembleRelease

      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          #signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          #alias: ${{ secrets.ALIAS }}
          #keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          #keyPassword: ${{ secrets.KEY_PASSWORD }}
          signingKeyBase64: ${{ secrets.SIGNINGKEYBASE64 }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTOREPASSWORD }}
          keyPassword: ${{ secrets.KEYPASSWORD }}
        env:
          # override default build-tools version (33.0.0) -- optional
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: app/build/outputs/apk/release/